name: fleetctl-gitops
description: Runs fleetctl gitops to apply configuration to Fleet

runs:
  using: "composite"
  steps:
    - name: Install fleetctl
      shell: bash
      run: npm install -g fleetctl

    - name: Configure fleetctl
      shell: bash
      run: fleetctl config set --address ${{ env.FLEET_URL }} --token ${{ env.FLEET_API_TOKEN }}

    - name: Run fleetctl gitops commands
      shell: bash
      run: ./workflow.sh
