name: 'Apply latest configuration to Fleet'

on:
#  push:
#    branches:
#      - main
  workflow_dispatch: # allows manual triggering

defaults:
  run:
    shell: bash

# Add FLEET_URL and FLEET_API_TOKEN to the repository secrets.
# In addition, specify or add secrets for all the environment variables that are mentioned in the global/team YAML files.
env:
  FLEET_SSO_METADATA: ${{ secrets.FLEET_SSO_METADATA }}
  FLEET_GLOBAL_ENROLL_SECRET: ${{ secrets.FLEET_GLOBAL_ENROLL_SECRET }}
  FLEET_WORKSTATIONS_ENROLL_SECRET: ${{ secrets.FLEET_WORKSTATIONS_ENROLL_SECRET }}
  FLEET_WORKSTATIONS_CANARY_ENROLL_SECRET: ${{ secrets.FLEET_WORKSTATIONS_CANARY_ENROLL_SECRET }}
  FLEETCTL: ./fleetctl

jobs:
  fleet-gitops:
    runs-on: ubuntu-latest
    steps:
      - name: Apply latest configuration to Fleet
        uses: ./github/actions
