name: 'Apply latest configuration to Fleet (as ref)'

on:
  #  push:
  #    branches:
  #      - main
  workflow_dispatch: # allows manual triggering

defaults:
  run:
    shell: bash

# Limit permissions of GITHUB_TOKEN.
permissions:
  contents: read

jobs:
  fleet-gitops:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout our repository
        uses: actions/checkout@v4

      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: getvictor/fleet-gitops
          path: ${{ github.workspace }}/fleet-gitops

      - name: Apply latest configuration to Fleet
        uses: ${{ github.workspace }}/fleet-gitops/.github/actions
        with:
          working-directory: ${{ github.workspace }}/fleet-gitops
          FLEET_URL: ${{ secrets.FLEET_URL }}
          FLEET_API_TOKEN: ${{ secrets.FLEET_API_TOKEN }}
          FLEET_SSO_METADATA: ${{ secrets.FLEET_SSO_METADATA }}
          FLEET_GLOBAL_ENROLL_SECRET: ${{ secrets.FLEET_GLOBAL_ENROLL_SECRET }}
          FLEET_WORKSTATIONS_ENROLL_SECRET: ${{ secrets.FLEET_WORKSTATIONS_ENROLL_SECRET }}
          FLEET_WORKSTATIONS_CANARY_ENROLL_SECRET: ${{ secrets.FLEET_WORKSTATIONS_CANARY_ENROLL_SECRET }}
          FLEETCTL: ${{ github.workspace }}/fleet-gitops/fleetctl
          FLEET_GITOPS_DIR: ${{ github.workspace }}/it-and-security
